CSV file added for team Kimehecc
ftsrg-csi/BenchmarkDataPool pull request #20
Opened 2020-10-29 13:27 UTC by awerv

2020-10-29 16:17 UTC, aklenik requested changes
See the review comments.

2020-10-29 16:17 UTC, aklenik commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize2,Pride1_Sense1,43410395234723,Kimehecc,Pride1_Sense1
Same event, different time?

2020-10-29 16:17 UTC, aklenik commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize1,Pride1_Sense1,43410394225291,Kimehecc,Pride1_Sense1
Please insert the header.

2020-10-29 16:17 UTC, aklenik commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize2,Pride1_Sense1,43410394509884,Kimehecc,Pride1_Sense1
`Tokenize[1-2]` takes only a single input, so the 3rd column value should be either `Pride1` or `Sense1`.
1. Can you separate this in your implementation? 
2. If not (because it's too much work), can you manually split them? For example, if `Tokenize2` always takes the `SenseX` input, then this value would be `Sense1`. Is this deterministic?

2020-10-29 16:35 UTC, aklenik commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize2,Pride1_Sense1,43410394509884,Kimehecc,Pride1_Sense1
Please ignore this for the moment.

2020-10-29 16:56 UTC, awerv commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize2,Pride1_Sense1,43410395234723,Kimehecc,Pride1_Sense1
It was a copy-paste issue, the main component also logs these events with the names of the tokenizers; the earlier ones were removed

2020-10-29 16:56 UTC, awerv commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize1,Pride1_Sense1,43410394225291,Kimehecc,Pride1_Sense1
Header inserted

2020-10-29 17:00 UTC, awerv commented on csvs/Kimehecc.csv
> +QUEUE,Tokenize2,Pride1_Sense1,43410394509884,Kimehecc,Pride1_Sense1
The ids were modified after the execution, the implementation works with numeric ids. Modifying them would be too much work, but Pride* goes to Tokenizer1 and Sense* goes to Tokenizer2 deterministically. We won't edit it manually, since this effects half of the 900 lines of log messages, but it can be fixed with a script.

2020-11-02 07:03 UTC, aklenik requested changes
36 rows are still missing somewhere (1,5 measurement).

2020-11-02 12:29 UTC, aklenik approved these changes

2020-11-02 12:29 UTC, merged